### PR TITLE
[NCLSUP-268] Enable Scp-like urls to be created

### PR DESCRIPTION
**Pull request by dominikbrazdil**
### All Submissions:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/repour/wiki/Changelog) for your change?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
Thanks @dominikbrazdil for the changes! They look good.

Could you please run this to fix the CI failure (it's due to code formatting):
```
poetry run tox

# yeah run it twice
poetry run tox
```

Don't worry if it fails the first time. That should make the CI happier and I'll merge it. I've also taken an action to add a unit test for this. Stupid me didn't add it in the original PR.

**Comment by dominikbrazdil** [comment]
@thescouser89 Thanks for the review and the advice :) I'll checkout the test and fix this PR

**Comment by michalovjan** [comment]
Hi @dominikbrazdil ! Scp-like urls are identified by that `:` with no port after and not the `git@` protocol. It's technically not even URL so I am not sure if urlparse is sufficient. In Orch I've had to write a custom parser because of that.

**Comment by dominikbrazdil** [comment]
Oh, I see @michalovjan, I thought that the ":" is connected with the url not having any protocol (therefore starting with git@). I will remake the check for the collon as well. Thanks for noticing

**Review by thescouser89 — APPROVED** [review]

**Comment by thescouser89** [comment]
LGTM! THanks @michalovjan  for the extra :eyes:  for the review! :)

**Pull request merged**
