### PR TITLE
[NCL-2981] Add endpoint /cloneadjust

### PR DESCRIPTION
**Pull request by thescouser89**
This endpoint allows a user to sync and optionally run PME on the
output.

If the ref is a branch, the branch will be pushed to the target repo. If
the ref is a tag, the tag will be pushed to the target repo. If the ref
is a SHA, a branch will be created and named 'branch-<ref>' and pushed
to the target repo. The latter is required to get a particular commit to
the target repository.

The adjust parameter, when enabled, will run PME, and the result is put
inside the response in key 'adjust_result'. The content of
'adjust_result' is exactly the same as the output for the '/adjust'
endpoint.

### CODE REVIEW

**Comment by jbartece** [comment]
@matejonnet  @jbrazdil  What do you think about the branch-<hash> created if the external revision is hash?
It should work for us, right? As the hash will be the same internally, so the build can be run from it.

**Comment by thescouser89** [comment]
I'd just like to add that while the branch is created, it is not referred to in the reply from repour. I have to use the branch creation hack to get a particular commit id to the target repository.

**Comment by thescouser89** [comment]
BTW, the documentation for the new endpoint can be found here: https://github.com/thescouser89/repour/blob/685e208d09a09ef7fed95e021f16f679507f2ce3/README.asciidoc#clone-adjust

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by jbartece** [comment]
@thescouser89 Sounds good :-). Even better than we planned probably. I don't see any issues with this solution.

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
(I'm testing the repour Github PR test thing, should be good to merge)

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
Tests are now running 🎆 🎆 🎆 

I need to add some tests for `/cloneadjust` 🤐

**Pull request merged**
