### PR TITLE
[NCL-3159] Create tag that matches ver for /adjust

### PR DESCRIPTION
**Pull request by thescouser89**
Repour currently creates a commit and tag after and adjustment is done
to a repository. The tag name is using the format 'repour-<commitid>'.

This commit attempts to change the tag name format to
'\<version>'. The new tag format is more meaningful and should
help humans better understand what the tag is used for.

The version information is extracted only when we use PME for the
adjustment phase. PME generates a result JSON file that contains the
version of the Java project after processing. That version is extracted
from the JSON file and is used to generate the new tag name.

### CODE REVIEW

**Comment by pgier** [comment]
I'd prefer that we don't prepend "repour" to the tag name.  Since we are appending the -redhat-X suffix to the version it should already be unique.  And if it's not unique, then repour should return an error saying that we are potentially conflicting with an already released version.
I think adding the name "repour" in the tag annotation comment (if it's not already included) should make it clear enough that the tag was automatically generated.

**Comment by thescouser89** [comment]
@pgier Gotcha! we don't use tag annotation, but this can be done. I'll do the necessary changes. Will push the new changes here and will edit the description.

**Comment by jbartece** [comment]
As for me +1 for "not to add the repour prefix"

**Comment by thescouser89** [comment]
Repour will now create tag with '<version>' and add to its annotated tag message that the tag was created by repour

**Comment by pgier** [comment]
LGTM!

**Comment by thescouser89** [comment]
Thanks for the review everyone! :)

**Pull request merged**
