### PR TITLE
[NCL-5839] Add git submodule support

### PR DESCRIPTION
**Pull request by thescouser89**
Special thanks to @rnc for his guidance on it!

### All Submissions:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/repour/wiki/Changelog) for your change?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by rnc** [comment]
Had a thought ... how should we / do we handle updates ? i.e. a 'development/master' branch? Tags I guess shouldn't be an issue.

**Comment by thescouser89** [comment]
Hmm from what I understand with git submodules is that the parent sets the commit id of the submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules). So in this case the parent repository is still tracking a specific commit, unless updated in the parent repository to the 'latest' commit in the submodule.

**Comment by rnc** [comment]
Hmmm yeah I think so - so if its stored commit x, and repour has made a fat repository - what happens if the user wishes to bring in updates to the branch? Can repour handle that? What happens if the branch has updated the sub-module index?

**Comment by thescouser89** [comment]
Repour pushes the fat repository commit + alignment commit in a tag. Those 2 commits are not in any branch. So if the branch we are building from (and that contains the .gitmodules file) has an updated submodule index, the rebuild will create a new updated fat repository commit first, then the alignment commit, and push it in another tag. We then build from that tag.

So whatever changes happen to the upstream / downstream branch containing .gitmodules file, Repour should be able to track it when going through the alignment phase.

I hope I understood the scenario you were describing :) If not, please let me know!

**Pull request merged**
