### PR TITLE
[NCL-8044] Fix internal scm url handling issues

### PR DESCRIPTION
**Pull request by pkocandr**
### All Submissions:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/repour/wiki/Changelog) for your change?
* [x] Have you added unit tests for your change?

### CODE REVIEW

**Review by thescouser89 — APPROVED** [review]

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Pull request merged**
