### PR TITLE
[NCL-8044] Add endpoint to create new repository in GitLab

### PR DESCRIPTION
**Pull request by pkocandr**
### All Submissions:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/repour/wiki/Changelog) for your change?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by pkocandr** [comment]
retest this please

**Comment by thescouser89** [comment]
@pkocandr looks good! The only thing I'd like to see is the dependency gitlab being added:

You can do so by running:
```
$ poetry add gitlab
```

Otherwise, :+1: looking forward to the new endpoint!

**Pull request merged**
